### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by dinpd** [Cretezy/cloudflare-d1-backup#3]
throw new Error(`D1 Error: ${body.errors
                  ^

Error: D1 Error: Could not route to /client/v4/accounts/undefined/d1/database/undefined/query, perhaps your object identifier is invalid?
    at fetchD1 (file:///Users/danitkis/.npm/_npx/9d37dc0424d96159/node_modules/@cretezy/cloudflare-d1-backup/dist/index.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createBackup (file:///Users/danitkis/.npm/_npx/9d37dc0424d96159/node_modules/@cretezy/cloudflare-d1-backup/dist/index.js:30:26)
    at async file:///Users/danitkis/.npm/_npx/9d37dc0424d96159/node_modules/@cretezy/cloudflare-d1-backup/dist/cli.js:30:16

**Comment by t0m0120** [comment]
@dinpd 
Are you sure you have set the following three things correctly?
The error message seems to be undefined

CLOUDFLARE_D1_ACCOUNT_ID
CLOUDFLARE_D1_DATABASE_ID
CLOUDFLARE_D1_API_KEY

**Comment by kr105** [comment]
For some reason it didn't work with env vars for me (like on the example) but setting the values on the .env file worked just fine!
